### Outline

-   Chosen Dataset & its Features/Characteristics

-   Multi Linear Regression Methods

-   Multi-dimensional Linear Regression Methods

-   Assessment/Conclusion

-   Appendix: Code

```{r}

{r}
#################
# Load packages
#################

install.packages("ggplot2", repos = "http://cran.r-project.org")
install.packages("DescTools", repos = "http://cran.r-project.org")
install.packages("gridExtra", repos = "http://cran.r-project.org")
install.packages("tune", repos = "http://cran.r-project.org")

library(ggplot2)
library(tibble)
library(rsample)
library(parsnip)
library(dplyr)
library(Metrics)
library(caret)
library(DescTools)
library(gridExtra)
library(recipes)
library(magrittr)

add_recipe <- function(x, recipe, ..., blueprint = NULL) #{
  #check_dots_empty()
  #validate_recipes_available()
  #action <- new_action_recipe(recipe, blueprint)
  #add_action(x, action, "recipe")
#}

tune_grid <- function(object, ...){}
select_best <- function(x, ...){}
finalize_model <- function(x, ...){}
grid_regular <- function(x, ...){}

#fit <- function(x, data = NULL, model = "default", task = "default", 
#    search = "heuristic", mpar = NULL, feature = "none", 
#    scale = "default", transform = "none", 
#    created = NULL, fdebug = FALSE, ...)

# Calculate linear function
linear_model <- lm(n_eggs ~ n_hens, data = filtered_eggs_prod)
summary(linear_model)
```

```{r}

# Me removing just "hatching eggs" column because I'm only accounting for caged egg production. 

# This was if I was going to do a 1/3 train and 2/3 test 
numTrain <- 55
numTest <- length(X) - numTrain

# For reproducibility
set.seed(123)

# Start by creating a 1/3 split
split_obj <- initial_split(data, prop = numTrain/length(X))
```
